## Config do resilience4 via yml
resilience4j.retry:
  instances:
    secondCustomRetryConfig:
      maxAttempts: 4
      waitDuration: 3s
      ignoreExceptions:
        - com.example.demo.exception.IgnoredException
    thirdCustomRetryConfig:
      maxAttempts: 3
      waitDuration: 1s
#      resultPredicate: com.example.demo.config.retry.RetryCondition